import React from 'react';
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import { RoutesObj } from '../routes';
import { ProtectedAdminRoute } from './ProtectedAdminRoute';
import { AuthProvider } from './useAuth';
import { ProtectedPublicRoute } from './ProtectedPublicRoute';

const CusRoutes = () => {
  return (
    <BrowserRouter>
      <AuthProvider>
        <Routes>
          <Route element={<ProtectedPublicRoute />}>
            <Route
              exact
              path={RoutesObj.home.path}
              element={RoutesObj.home.component}
            />
            <Route
              exact
              path={RoutesObj.userDashboard.path}
              element={RoutesObj.userDashboard.component}
            />
            <Route
              exact
              path={RoutesObj.userProfile.path}
              element={RoutesObj.userProfile.component}
            />
            <Route
              exact
              path={RoutesObj.pricingPage.path}
              element={RoutesObj.pricingPage.component}
            />
            <Route
              exact
              path={RoutesObj.jobDetail.path}
              element={RoutesObj.jobDetail.component}
            />
            <Route
              exact
              path={RoutesObj.resourceCenter.path}
              element={RoutesObj.resourceCenter.component}
            />
            <Route
              exact
              path={RoutesObj.resourceDetail.path}
              element={RoutesObj.resourceDetail.component}
            />
          </Route>
          <Route
            exact
            path={RoutesObj.Root.path}
            element={RoutesObj.Root.component}
          />
          <Route
            exact
            path={RoutesObj.login.path}
            element={RoutesObj.login.component}
          />
          <Route
            exact
            path={RoutesObj.linkedInRedirect.path}
            element={RoutesObj.linkedInRedirect.component}
          />
          <Route
              exact
              path={RoutesObj.adminLogin.path}
              element={RoutesObj.adminLogin.component}
            />
          <Route
            exact
            path={RoutesObj.forgotPassword.path}
            element={RoutesObj.forgotPassword.component}
          />
          <Route
            exact
            path={RoutesObj.resendConfirmation.path}
            element={RoutesObj.resendConfirmation.component}
          />
          <Route
            exact
            path={RoutesObj.resetPassword.path}
            element={RoutesObj.resetPassword.component}
          />
          <Route
            exact
            path={RoutesObj.registerUser.path}
            element={RoutesObj.registerUser.component}
          />
          <Route
            exact
            path={RoutesObj.confirmEmail.path}
            element={RoutesObj.confirmEmail.component}
          />
          <Route
            exact
            path={RoutesObj.testScreen.path}
            element={RoutesObj.testScreen.component}
          />
          <Route
            exact
            path={RoutesObj.Health.path}
            element={RoutesObj.Health.component}
          />
          <Route
            exact
            path={RoutesObj.formCompleted.path}
            element={RoutesObj.formCompleted.component}
          />
          <Route
            exact
            path={RoutesObj.checkOut.path}
            element={RoutesObj.checkOut.component}
          />
          <Route
            exact
            path={RoutesObj.paymentStatus.path}
            element={RoutesObj.paymentStatus.component}
          />
          <Route
            exact
            path={RoutesObj.editorDemo.path}
            element={RoutesObj.editorDemo.component}
          />

          <Route element={<ProtectedAdminRoute />}>
            <Route
              exact
              path={RoutesObj.adminDashboard.path}
              element={RoutesObj.adminDashboard.component}
            />
            <Route
              exact
              path={RoutesObj.adminJobPortal.path}
              element={RoutesObj.adminJobPortal.component}
            />
            <Route
              exact
              path={RoutesObj.createEditJob.path}
              element={RoutesObj.createEditJob.component}
            />
            <Route
              exact
              path={RoutesObj.createEditResource.path}
              element={RoutesObj.createEditResource.component}
            />
            <Route
              exact
              path={RoutesObj.adminResourceCenter.path}
              element={RoutesObj.adminResourceCenter.component}
            />
            <Route
              exact
              path={RoutesObj.adminOneToOne.path}
              element={RoutesObj.adminOneToOne.component}
            />
          </Route>
        </Routes>
      </AuthProvider>
    </BrowserRouter>
  );
};

export default CusRoutes;
