describe.only('Login', () => {
  it('Login success', () => {
    cy.visit('https://app.d.getboardwise.com/login')
    cy.get("#email").type("umar.javed@fusiontech.global")
    cy.get("#email").should("have.value", "umar.javed@fusiontech.global")
    cy.get("#password").type("Liverpool@1")
    cy.get("#password").should("have.value", "Liverpool@1")
    cy.get("#loginBtn").click()
    cy.url().should("include","/userdashboard")
  })
  it('Login failure 1', () => {
    cy.wait(500)
    cy.visit('https://app.d.getboardwise.com/login')
    cy.get("#email").type("umar.javed@fusiontech.global")
    cy.get("#email").should("have.value", "umar.javed@fusiontech.global")
    cy.get("#loginBtn").click()
    cy.get(".errorTxt")
  })
  it('Login failure 2', () => {
    cy.wait(500)
    cy.visit('https://app.d.getboardwise.com/login')
    cy.get("#password").type("Liverpool@1")
    cy.get("#password").should("have.value", "Liverpool@1")
    cy.get("#loginBtn").click()
    cy.get(".errorTxt")
  })
  it('Login failure 3', () => {
    cy.wait(500)
    cy.visit('https://app.d.getboardwise.com/login')
    cy.get("#loginBtn").click()
    cy.get(".errorTxt")
  })
})