export const userJobTypes = {
  USER_JOB_ONCHANGE: 'USER_JOB_ONCHANGE',
  JOB_FILTER_VALUE: 'JOB_FILTER_VALUE',
  SELECTED_TITLES: 'SELECTED_TITLES',
  SELECTED_SKILLS: 'SELECTED_SKILLS',
  SELECTED_INDUSTRIESS: 'SELECTED_INDUSTRIESS',
  SELECTED_LOCATIONS: 'SELECTED_LOCATIONS',
  SELECTED_SORTRELEVANTTYPE: 'SELECTED_SORTRELEVANTTYPE',
  SELECTED_SORTRECENTTYPE: 'SELECTED_SORTRECENTTYPE',
  CLEAR_FILTER_VALUE: 'CLEAR_FILTER_VALUE',
};
